--- # Copy this to "config.yml" before modifying!

# Booleans may be yes/no, on/off, or true/false

# If yes, the bot will use token.txt to start - devtoken.txt otherwise
public: yes

# Set your command prefix here
# "public" for if public is on, "developer" if its off
prefixes:
    public: "-"
    developer: "$"

# Allows queueing entire Spotify playlists
# This currently takes a long time (~1-2 seconds per track) to do, so it's disabled by default
allow-spotify-playlists: yes

# Limit the amount of tracks Spotify playlists can have before queueing
spotify-playlist-limit: 40

# Forces Spotify links to not find an automatic YouTube match,
# and will always trigger the choice menu
force-no-match: no

# Automatically queues the top result of a Spotify-YouTube match,
# regardless of how close the match is
use-top-match: yes

# Set various options for output logs
logging-options:
    # Everything still outputs to vimusbot.log regardless of the options below
    # Toggle outputting logs from bot.py and/or spoofy.py to the console
    show-console-logs:
        bot.py: yes
        spoofy.py: yes
    # Ignore logs from specific functions (blue text in logs, by default)
    ignore-logs-from:
        - "search_ytmusic"
    # Choose your preferred log colors
    colors:
        no-color: no # Disables all message coloring
        # Run "python3 palette.py --show" to see options
        bot.py: "yellow" # For the [bot.py] part
        spoofy.py: "lime" # For the [spoofy.py] part
        warn: "gold" # For non-serious warning messages
        error: "red" # For tracebacks and/or fatal errors
        timer: "magenta" # The time between logs at the end of each message
        function: "blue" # For function names